// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ_bH5tciJNjBM_ur-3SFKQ-VgRMNDgRQ',
    appId: '1:78078867851:web:d93abca805e0a35e2f578e',
    messagingSenderId: '78078867851',
    projectId: 'studyhub-57c3d',
    authDomain: 'studyhub-57c3d.firebaseapp.com',
    storageBucket: 'studyhub-57c3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtSXuhoLoWBFyEKJGCOytt6LNP0f7yCYU',
    appId: '1:78078867851:android:97c5a3d5351ceeee2f578e',
    messagingSenderId: '78078867851',
    projectId: 'studyhub-57c3d',
    storageBucket: 'studyhub-57c3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9blF47VKUBNzv-gC_7dmgFubs0gzHtbg',
    appId: '1:78078867851:ios:e3de8f5be5bd45732f578e',
    messagingSenderId: '78078867851',
    projectId: 'studyhub-57c3d',
    storageBucket: 'studyhub-57c3d.firebasestorage.app',
    iosBundleId: 'com.example.computers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9blF47VKUBNzv-gC_7dmgFubs0gzHtbg',
    appId: '1:78078867851:ios:e3de8f5be5bd45732f578e',
    messagingSenderId: '78078867851',
    projectId: 'studyhub-57c3d',
    storageBucket: 'studyhub-57c3d.firebasestorage.app',
    iosBundleId: 'com.example.computers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ_bH5tciJNjBM_ur-3SFKQ-VgRMNDgRQ',
    appId: '1:78078867851:web:273b6fa8278260942f578e',
    messagingSenderId: '78078867851',
    projectId: 'studyhub-57c3d',
    authDomain: 'studyhub-57c3d.firebaseapp.com',
    storageBucket: 'studyhub-57c3d.firebasestorage.app',
  );
}
